# ===========
# Import
# ===========
from sqlalchemy.orm import Session
from sqlalchemy import select
from ..db.models import (
  Run,
  Interaction,
  InteractionExecution,
  HttpRequest,
  HttpResponse,
)

from .save_to_txt import save_to_txt


# ===========
# Functions
# ===========
def run_analysis(db: Session, exploration_run_id: int, replay_run_id: int):
  network_results = find_network_differences(db, exploration_run_id, replay_run_id)
  # [TODO] dom_results = find_dom_differences(db)
  
  save_to_txt(network_results)
  
  
    
def find_network_differences(db: Session, exploration_run_id: int, replay_run_id: int):
  results = collect_network_comparison_pairs(db, exploration_run_id, replay_run_id)
  return results
  
      

def collect_network_comparison_pairs(db: Session, exploration_run_id: int, replay_run_id: int):
  
  """
    Find logical interactions that were executed in both the
    exploration and replay runs.

    For each common interaction, retrieve the HTTP responses
    generated by the two executions.

    Builds the pairs that will later be analyzed by a scoring function
    to detect BAC-related differences.
  """
  
  # [Get all InteractionExecution belonging to the two runs]
  
  # Example
  #   execution 1 → interaction 10 → exploration
  #   execution 2 → interaction 10 → replay
  #   execution 3 → interaction 11 → exploration
  #   execution 4 → interaction 11 → replay
  
  executions = db.execute(select(InteractionExecution).where(InteractionExecution.run_id.in_([exploration_run_id, replay_run_id]))).scalars().all()
  
  # [Group executions by logical interaction]
  
  # Example:
  #   interaction_id: {
  #     exploration_run_id: execution_1,
  #     replay_run_id: execution_2
  #   }
  
  grouped = {}

  for execution in executions:
    grouped.setdefault(execution.interaction_id, {})[execution.run_id] = execution
  
  
  # [Build the comparison dataset]
  # We only consider interactions executed in BOTH runs.
  # Interactions present in only one run are skipped for now.
  results = []

  for interaction_id, by_run in grouped.items():
    exploration_execution = by_run.get(exploration_run_id)
    replay_execution = by_run.get(replay_run_id)

    # The interaction was not executed in both runs
    if not exploration_execution or not replay_execution:
      continue

    # [Retrieve HTTP responses generated by each execution]
    exploration_responses = get_responses_for_execution(db, exploration_execution.id)
    replay_responses = get_responses_for_execution(db, replay_execution.id)

    results.append({
      "interaction_id": interaction_id,
      "exploration_execution_id": exploration_execution.id,
      "replay_execution_id": replay_execution.id,
      "exploration_responses": exploration_responses,
      "replay_responses": replay_responses,
    })

  return results

    
    
def get_responses_for_execution(db: Session, execution_id: int):
  stmt = select(HttpResponse).join(HttpRequest).where(HttpRequest.interaction_execution_id == execution_id)
  return db.execute(stmt).scalars().all()