# ===========
# Import
# ===========
from sqlalchemy.orm import Session
from sqlalchemy import select
from ..db.models import (
  HttpRequest,
  HttpResponse,
  InteractionExecution,
)

from urllib.parse import urlparse, parse_qs


def get_pairs(db: Session, type: str, exploration_run_id: int, replay_run_id: int):
  # Get all InteractionExecution belonging to the two runs
  executions = (db.execute(
    select(InteractionExecution)
    .where(InteractionExecution.run_id.in_([exploration_run_id, replay_run_id])))
    .scalars()
    .all())
  
  # Group executions by logical interaction
  grouped = {}

  for execution in executions:
    grouped.setdefault(execution.interaction_id, {})[execution.run_id] = execution
  
  # Build the comparison dataset
  # Interactions present in only one run are skipped
  results = []

  for interaction_id, by_run in grouped.items():
    exploration_execution = by_run.get(exploration_run_id)
    replay_execution = by_run.get(replay_run_id)

    # The interaction was not executed in both runs
    if not exploration_execution or not replay_execution:
      continue

    # Retrieve HTTP responses generated by each common interaction
    if type == "network":
      exploration_http_events = get_http_for_execution(db, exploration_execution.id)
      replay_http_events = get_http_for_execution(db, replay_execution.id)

      results.append({
        "interaction_id": interaction_id,
        "exploration_execution_id": exploration_execution.id,
        "replay_execution_id": replay_execution.id,
        "exploration_http_events": exploration_http_events,
        "replay_http_events": replay_http_events,
      })
    elif type == "dom":
      # retrieve DOM state generated by each common interaction
      exploration_dom_states = get_dom_for_execution(db, exploration_execution.id)
      replay_dom_states = get_dom_for_execution(db, replay_execution.id)
      
      results.append({
        "interaction_id": interaction_id,
        "exploration_execution_id": exploration_execution.id,
        "replay_execution_id": replay_execution.id,
        "exploration_dom_states": exploration_dom_states,
        "replay_dom_states": replay_dom_states,
      })

  return results


def get_http_for_execution(db: Session, execution_id: int):
  stmt = (
    select(HttpRequest, HttpResponse)
    .join(HttpResponse, HttpResponse.request_id == HttpRequest.id)
    .where(HttpRequest.interaction_execution_id == execution_id)
  )

  return db.execute(stmt).all()



# Get initial and final DOM state, after target interaction
def get_dom_for_execution(db: Session, execution_id: int):
    execution = db.get(InteractionExecution, execution_id)

    if not execution:
      return None

    return {
      "from_state": execution.from_state,
      "to_state": execution.to_state,
    }